### ISSUE TITLE
Create a new record ,duplicate record saved in the database

### ISSUE THREAD

**Issue by cviacmob** [oogbox/odoo-mobile#1]
**Am create a  image with new record using mobile network having duplicate data saved in the database but WiFi connection have working , mobile network data have only problem.**

 OdooValues values = new OdooValues();
 values.put("post_code", mPostalCode.getText());
        client.create("ryot.master", values, new IOdooResponse() {
            @Override
            public void onResult(OdooResult result) {
                int serverId = result.getInt("result");
                Toast.makeText(getActivity(), "Save Successfully", Toast.LENGTH_LONG).show();
                getActivity().onBackPressed();

            }

        });

**Comment by bunny-oogbox** [comment]
Hello @cviacmob 
Yes, because you are on Mobile data it take some time and the request get timeout and it retries again.
When creating any record on the server with API call. Just change the retry policy for that request via
```java
client.withRetryPolicy(Integer requestTimeout, Integer maxRetry);
```
and set maxRetry to zero.
Like in your example:
```java
client.withRetryPolicy(50000, 0); // 50 second timeout and no retry if failed.
client.create("ryot.master", values, new IOdooResponse() {
...
...
```
When failed you get error in ``onError`` with ``Timout``

**Comment by cviacmob** [comment]
thanks for your help
